version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8888:8888"
    volumes:
      - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/home/rdavletshin/project/project.local
    restart: always
    depends_on:
      - php
      - postgres
  php:
    build: .docker
    restart: always
    volumes:
      - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - .:/home/rdavletshin/project/project.local
  composer:
    image: composer
    volumes:
      - .:/app
    command: install
  postgres:
    image: postgres:latest
    container_name: psql
    restart: always
    ports:
      - 5432
    volumes:
      - /var/lib/postgresql:/var/lib/postgresql
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "yfNL4W"
