version: '3'

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
          - "8888:8888"
        volumes:
          - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
          - .:/home/rdavletshin/project/project.local
        restart: always
        depends_on:
          - php
          - db
    php:
        build: .docker
        container_name: php
        volumes:
          - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
          - .:/home/rdavletshin/project/project.local
    composer:
        image: composer
        container_name: composer
        volumes:
          - .:/app
        command: install
    db:
        image: postgres:latest
        container_name: postgres
        ports:
          - 5432:5432
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
