GET http://project.local/notes
Content-Type: application/json

###

GET http://project.local/notes/2
Content-Type: application/json

###

POST http://project.local/notes
Content-Type: application/json

{
    "title": "title"
}

###

PUT  http://project.local/notes/2
Content-Type: application/json

{
    "title": "update"
}

###

DELETE  http://project.local/notes/20
Content-Type: application/json

###

