GET http://project.local/notes
Content-Type: application/json

###

GET http://project.local/notes/97
Content-Type: application/json

###

POST http://project.local/notes
Content-Type: application/json

{
    "title": "title"
}

###

PUT  http://project.local/notes/91
Content-Type: application/json

{
    "title": "title"
}

###

DELETE  http://project.local/notes/90
Content-Type: application/json

###

