GET http://project.local/notes/97
Content-Type: application/json

###

POST http://project.local/notes
Content-Type: application/json

{
    "title": "title"
}

###

GET http://project.local/notes
Content-Type: application/json

###


